version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: dev-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
submodules:
  include: all
  recursive: true
